local shell = require "gtmos_shell"
local os = require "gtmos_os"

local env = {
  _HOST = _HOST,
  ipairs = ipairs,
  next = next,
  pairs = pairs,
  pcall = pcall,
  tonumber = tonumber,
  tostring = tostring,
  type = type,
  unpack = unpack,
  print = print,
  error = error,
  dofile = dofile,
  select = select,
  setmetatable = setmetatable,
  getmetatable = getmetatable,
  load = load,
  keys = keys,
  io = io,
  rs = rs,
  printError = printError,
  debug = debug,
  peripheral = peripheral,
  textutils = textutils,
  fs = fs,
  read = read,
  sleep = sleep,
  settings = settings,
  write = write,
  colors = colors,
  colours = colours,
  term = term,
  shell = shell,
  coroutine = coroutine,
  string = string,
  table = table,
  math = math,
  os = os
}
env._G = env
env._ENV = env
return env